### ISSUE TITLE
Not building hourlies

### ISSUE THREAD

**Issue by Kalanyr** [hax0kartik/luma-hourlies#10]
The last hourly is https://github.com/AuroraWright/Luma3DS/commit/daaeb978346550e9c163d4eea2421d36fac02869 

but the last build here is from 5 days ago. Not sure if this is because the current Luma repository state isn't building or if it your build process is broken but thought it was worth reporting

**Comment by hax0kartik** [comment]
Uh-oh.

**Comment by hax0kartik** [comment]
Should be fixed now, thanks for reporting!
