### ISSUE TITLE
POKEMON ALFA SAPPHIRE THAT I BOUGHT TODAY IT CRASHES ERRDISP

### ISSUE THREAD

**Issue by Dani110192** [hax0kartik/luma-hourlies#11]
![image](https://user-images.githubusercontent.com/80990750/111850924-7e344d80-8909-11eb-9188-73d8f7f9b593.jpg)
![image](https://user-images.githubusercontent.com/80990750/111850954-9310e100-8909-11eb-9b09-86141e13560b.jpg)

i have luma updated 10.2.1 and boot9strap i tried with and without sd card. Pls help.

thanks.

**Comment by Dani110192** [comment]
I went to the shop today, and i changed the game and now it starts and i can choose a language and then same crashs.

help please.

**Comment by hax0kartik** [comment]
Try changing your sd card with a new one

**Comment by Dani110192** [comment]
I tried right now, I formatted the other sd card, and i also tried without card as well same crash, in two different nintendo, new 3ds and new 2ds xl something happens with luma 3ds and that cartdrige game.

**Comment by hax0kartik** [comment]
The error you're getting is usually due to a bad cartridge or sd, try a different cartridge and see if it still crashes

**Comment by Dani110192** [comment]
I went to shop right now and i tried 2 games of alpha sapphire and still crash.. (if i try any other game it works, Pokemon ultraluna, ultrasun, x or y) i tried in different 2ds or 3ds that have luma3ds) i will try today in a 3ds xl without hack and probably will work.. the issue is the hack/luma3ds with that original game cartdrige alpha sapphire...

**Comment by Dani110192** [comment]
It doesn’t work on an original nintendo neither lol that’s weird...

**Comment by Dani110192** [comment]
I went to the shoo again, after trying 3 games on it works! Thanks for your time.
