### ISSUE TITLE
Black screen on Pkmn Omega Ruby

### ISSUE THREAD

**Issue by dynux90** [hax0kartik/luma-hourlies#12]
Model: New 2DS XL
fastboot3ds v1.2
Luma3DS v244-luma3ds-01661bb

Content from: errdisp.txt

Error type: generic

Process ID: 39
Process name: sango-1
Process title ID: 0x000400000011c400

Address: 0x0012884c
Error code: 0xd900458b

**Comment by fsilletti** [comment]
same problem

**Comment by hax0kartik** [comment]
Try older commit and check if that works?

**Comment by hax0kartik** [comment]
Also try the official luma release and see if that works

**Comment by dynux90** [comment]
> Also try the official luma release and see if that works

Same error with official

**Comment by dynux90** [comment]
> Try older commit and check if that works?

Tried 243-luma3ds-8e9a3bf same problem

**Comment by hax0kartik** [comment]
Then it is a issue with your game itself. Ask on nh discord for help

**Comment by dynux90** [comment]
> Then it is a issue with your game itself. Ask on nh discord for help

what is nh discord? can you grab me the link?
