### ISSUE TITLE
Not building hourlies (and CI disabled)

### ISSUE THREAD

**Issue by Kalanyr** [hax0kartik/luma-hourlies#13]
As of this report the last Luma commit was [44c1711](https://github.com/LumaTeam/Luma3DS/commit/44c171180567c672cb82d8f70281157845b0fcbf)  (which was within 24 hours) but the last hourly build was https://github.com/hax0kartik/luma-hourlies/releases/tag/246-luma3ds-b83a0ab in August 2021

The CI builds have also been disabled due to lack of inactivity for 60 days, so you may want to reenable those.

**Comment by hax0kartik** [comment]
I'm aware, but, seeing how luma is not being actively developed, I think it's better to not re-enable this project.
