### ISSUE TITLE
Did as supposed too, still getting the "Failed To Apply 1 Firm Patch " Error.

### ISSUE THREAD

**Issue by reisera** [hax0kartik/luma-hourlies#5]
Been working with a friend on her 2DS (cake slice ver.) and we followed Tech James' video on how to apply this file and we keep getting the error.  Is there anything else we can do?

**Comment by hax0kartik** [comment]
@reisera follow the steps on https://3ds.hacks.guide. Vguides are old are not up to date

**Comment by Multimegamander** [comment]
Luma 9.1 only supports 11.8/11.9, I think this should be closed as it's user error
