### ISSUE TITLE
help please!!!

### ISSUE THREAD

**Issue by danxilys** [hax0kartik/luma-hourlies#6]
this ... I have a problem I do not know if it can be solved or it has no fix it turns out that my 3ds had the error of failed to apply firm patch
and I "harregle" but after pressing start on the home screen of the luma (?) I found an error writting the comfiguration file and I despaired to delete the contents of my sd and now I see "error in mounting the sd card " I hope you can help me :(

**Comment by hax0kartik** [comment]
Get help here:- https://www.google.com/url?sa=t&source=web&rct=j&url=https://discordapp.com/invite/MWxPgEp&ved=2ahUKEwiRwpGbt-PgAhXZTn0KHSTjBjEQjjgwBXoECAkQAQ&usg=AOvVaw0law5sTxVCJuur3EXA21yh

**Comment by Multimegamander** [comment]
You need to system update and run luma 9.1, and your SD has write protection...
