### ISSUE TITLE
Departures with errors in several games

### ISSUE THREAD

**Issue by contra1980** [hax0kartik/luma-hourlies#8]
Hello! In version 203-luma3ds-2c8a1eb, it does not start (throws out with an error, does not reach the menu) Heroes of the ruins. And periodic emissions Metal Gear 3D
On standard Lum 3ds everything works, but cheats do not work)

**Comment by noirscape** [comment]
Hourlies are unsupported builds of Luma3DS. You are running these at your own risk.

If you don't want games randomly breaking, use stable builds.

**Comment by Margen67** [comment]
@hax0kartik @contra1980 Close this please.
